# Generated by Django 4.0.1 on 2022-06-05 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_swmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
