# Generated by Django 4.0.1 on 2022-06-06 03:49

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='swmodel',
            name='bodycount',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='swmodel',
            name='facecount',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='swmodel',
            name='filetype',
            field=models.IntegerField(default=0, validators=[core.models._validFileType]),
        ),
    ]
