# Generated by Django 4.0.1 on 2022-06-06 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_swmodel_bodycount_swmodel_facecount_swmodel_filetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='swmodel',
            name='rebuild_error',
            field=models.BooleanField(default=False),
        ),
    ]
